apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ava-server
    app.kubernetes.io/part-of: ava
    app.kubernetes.io/component: server
  name: ava-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  selector:
    app.kubernetes.io/name: ava-server
