apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ava-server
  namespace: ava-production
spec:
  encryptedData:
    openai.apikey: AgDWHqBvhHpDe5Tdu+G3+hd5Di7LXBU+eTCnQBDpyYbslFGfHt8kSnaPMxSiHZ/4Rme8Xhm0ajpnkxi/XGf37fW9d9z9wMhKihJNGjccdiZ+Yoz2AE9k6ymsnZv7AflZiyfc3AaMukVGsMIMMKC0PvoY6JmpxVud49LZZ6YUWKv78yrd2R4cAN/WbrprUUGTzT7Bn82lAv4h/LVI6XWSGqz0qh4ALKwoQGld4xaUaIZZ9+HuLuBsv65FN4KriPy7PWoxydSCpKW5WtCC+Flkiz9XYLLtTOZPM2Sv6G0XosEx4YPEAGuFaVQ+hD1jAKKJFB1tBwGn3GA6N8TitodsIzwUwXwhGBhvava75B9SCOfLOUOMm2StRzVASRlutEHVt60B8zcZhEjxSsp+ZEWaNGupj2VOTrcxnkZFL2eDRZWH1D3FHDx8vTKCOzgMCV+UkiKktqv8nGY7w3MUhDQnMHMI169Fjhnc9d+jCVK0E65hNsQNeL4aviFo1Lz4+PonLVBM96STfCUBXu2aT4bpxi+xP2nxxpYlB0395dm22Jzhd6AQ16QzHM1y3P2Z06ujCRuG6DquPe2fLgIwTmnGlSNLM+xVKyR1nR79selqwJgQG3S402wN7D8PFnikUJz9go17iwjMWpLteB/Vsgr1GEHOHD6AN71R84LMmZPa5xu9WZOQdU28Hjf4yDlzOPa550IrZnQLFdKlhDnJmziefBqK9IrsjoG5xe1JgYYF1AuDGmlsmhOxV+NW9r6mZkEPafRp+8I=
    serpapi.apikey: AgDTmXZPWT0B3PDiEVnBzmp0a8oxSjddFxZT1patkMUpzR/9fQhfsMQZ3vZhnRMHPeNDnvtCDMmmFQuzfvxJ+VX0GLQgs/TrDCiC5I1WeYkwEMKTayCDbCdafoIQypLE9jfCT8M+1/VSl1HD5Q0KG3d40HL71uIm2APQAzf0ySHxzshe0wazDDjmIO6nsGhgTy6a4EkFfAyo02jYSzc9qOWGSB8QKIGCg+VCYz6UXRUmQWoKfNTnL3pUUgrXo97YPN71s6edL5q2CmlzQzl42cERuvBbH6QRe6eUOydlRvEfY81Oim4sYB2aItg6CIRvpQ90aVzElrHhxSyR2we3oWE5TcZcuzA3UUMya56AsBWTRhzVU+l5lgTazcxPdxXpp7aR3x2lIn+L+Z8PddmyMQrgkPCQPUaN6y/R38fZbY7p1kmLjlIiXSKuAcvf31dGE5ZaP6iUQNelipRGJoNglhHuMNnKxeKJTc24jk6Q4YcBEGsViQ9WXxpkgm9So0ScLojJh5nYpnNtW7cse9LxLer22sPz6twCJhydp4EkVRGxzGQIAwqJB9E7CwqOyyf7U0UPoYNR5OPpQN4/YDk8sIFdX+DfIKb1qIECkOcVeCmR3vcad1QN6E+9xyHt20rnXKXQSuYQFx9m/7/yHC7kLQKwIJwXIZmF9QyTJOFVvxbntTktpjX+uGwFI5zszL6P9t9uns8mXhUUgpB/2tdCCgclWEvnHM8LmpTznXPyA/6sS45X7KIiUAw11C11fJ59TRoxjQT5nXP8MMSfO327vZOu
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: ava-server
        app.kubernetes.io/part-of: ava
      name: ava-server
      namespace: ava-production
