apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ava-client
    app.kubernetes.io/part-of: ava
    app.kubernetes.io/component: client
  name: ava-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ava-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ava-client
    spec:
      serviceAccountName: ava-client
      containers:
        - name: ava-client
          image: samgamage/ava-client
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
