apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ava-staging

resources:
  - ../bases/client
  - ../bases/server
  - ../bases/cache
  - namespace.yaml
  - ingress.yaml

patchesStrategicMerge:
  - config.yaml

images:
  - name: samgamage/ava-server
    newTag: v0.1.0-beta.2
  - name: samgamage/ava-client
    newTag: v0.1.0-beta.2
