name: release

on:
  release:
    types: [published]

jobs:
  build-push-release-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: samgamage/ava-server:{{github.ref}}
      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:client"
          push: true
          tags: samgamage/ava-client:{{github.ref}}
